version: '3.8'

services:
  postgres-db:
    image: postgres:16-alpine
    container_name: aws_catalog_postgres
    restart: always
    environment:
      POSTGRES_DB: aws_catalog_db
      POSTGRES_USER: catalog_user
      POSTGRES_PASSWORD: catalog_password_2026
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U catalog_user -d aws_catalog_db"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
    driver: local